@host = http://127.0.0.1:8080/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "prim",
  "password": "admin123"
}


### Token verification
GET {{host}}/verify-token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InByaW0iLCJpZCI6MTAwLCJleHAiOjE2NTI5NjczNjV9.Mu_EMaxXlcv15hizOfjMlZRY1C_wnoRVOaQ79oCbdbs HTTP/1.1

